config/routes.rb
Newsapp::Application.routes.draw do
  resources :headlines
root :to => "headlines#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :headline
end

app/models/headline.rb
class Headline < ActiveRecord::Base
has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/headlines_controller.rb
class HeadlinesController < ApplicationController
  # GET /headlines
  # GET /headlines.xml
  def index
    @headlines = Headline.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @headlines }
    end
  end

  # GET /headlines/1
  # GET /headlines/1.xml
  def show
    @headline = Headline.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @headline }
    end
  end

  # GET /headlines/new
  # GET /headlines/new.xml
  def new
    @headline = Headline.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @headline }
    end
  end

  # GET /headlines/1/edit
  def edit
    @headline = Headline.find(params[:id])
  end

  # POST /headlines
  # POST /headlines.xml
  def create
    @headline = Headline.new(params[:headline])

    respond_to do |format|
      if @headline.save
        format.html { redirect_to(@headline, :notice => 'Headline was successfully created.') }
        format.xml  { render :xml => @headline, :status => :created, :location => @headline }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @headline.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /headlines/1
  # PUT /headlines/1.xml
  def update
    @headline = Headline.find(params[:id])

    respond_to do |format|
      if @headline.update_attributes(params[:headline])
        format.html { redirect_to(@headline, :notice => 'Headline was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @headline.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /headlines/1
  # DELETE /headlines/1.xml
  def destroy
    @headline = Headline.find(params[:id])
    @headline.destroy

    respond_to do |format|
      format.html { redirect_to(headlines_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/headlines_helper.rb
module HeadlinesHelper
end

app/views/headlines/_form.html.erb
<%= form_for(@headline) do |f| %>
  <% if @headline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@headline.errors.count, "error") %> prohibited this headline from being saved:</h2>

      <ul>
      <% @headline.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_area :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/headlines/edit.html.erb
<h1>Editing headline</h1>

<%= render 'form' %>

<%= link_to 'Show', @headline %> |
<%= link_to 'Back', headlines_path %>

app/views/headlines/index.html.erb
<h1>Listing headlines</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Description</th>
    <th>Title</th>
    <th>Link</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @headlines.each do |headline| %>
  <tr>
    <td><%= headline.date %></td>
    <td><%= headline.description %></td>
    <td><%= headline.title %></td>
    <td><%= headline.link %></td>
    <td><%= link_to 'Show', headline %></td>
    <td><%= link_to 'Edit', edit_headline_path(headline) %></td>
    <td><%= link_to 'Destroy', headline, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Headline', new_headline_path %>

app/views/headlines/new.html.erb
<h1>New headline</h1>

<%= render 'form' %>

<%= link_to 'Back', headlines_path %>

app/views/headlines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @headline.date %>
</p>

<p>
  <b>Description:</b>
  <%= @headline.description %>
</p>

<p>
  <b>Title:</b>
  <%= @headline.title %>
</p>

<p>
  <b>Link:</b>
  <%= @headline.link %>
</p>


<%= link_to 'Edit', edit_headline_path(@headline) %> |
<%= link_to 'Back', headlines_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Newsapp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>